# Generated by Django 4.0.3 on 2022-03-10 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='total_rating',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
