# Generated by Django 4.0.3 on 2022-03-10 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_food_total_rating_delete_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='total_rating',
        ),
    ]
