# Generated by Django 4.0.2 on 2022-03-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_remove_question_image_question_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='images',
            field=models.ImageField(blank=True, default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
