# Generated by Django 4.0.2 on 2022-03-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_alter_question_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
