# Generated by Django 4.0.2 on 2022-03-11 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_like'),
        ('forum', '0005_alter_question_images'),
    ]

    operations = [
    ]
